package com.ines.skillmatch_offres_service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

// JPA entity representing a job offer. Mapped to the "offres" table.
@Entity
@Table(name = "offres")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Offre {

    // Primary key, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ID of the company that posted this offer (foreign key to Entreprise service).
    @Column(name = "entreprise_id", nullable = false)
    private Long entrepriseId;

    // ID of the user (company representative) who created this offer. Stored in DB for notifications.
    @Column(name = "user_id")
    @JsonProperty("userId") // Forces JSON serialization to use "userId" key instead of "user_id".
    private Long userId;

    // Offer title (required).
    @Column(nullable = false)
    private String titre;

    // Full description of the job, stored as TEXT (large string).
    @Column(columnDefinition = "TEXT", nullable = false)
    private String description;

    // Required skills, stored as TEXT (comma-separated or list string).
    @Column(name = "competences_requises", columnDefinition = "TEXT")
    private String competencesRequises;

    // Minimum education level required for this position.
    @Column(name = "niveau_requis")
    private String niveauRequis;

    // Salary information (e.g., "45k - 55k €").
    private String salaire;

    // Whether the offer is currently active (soft-delete flag). Defaults to true.
    @Builder.Default
    private Boolean active = true;

    // Publication date of the offer. Defaults to current timestamp.
    @Column(name = "date_publication")
    @Builder.Default
    private LocalDateTime datePublication = LocalDateTime.now();

    // -------------------- TRANSIENT FIELDS (not stored in DB) --------------------
    // These are populated dynamically when retrieving offers (e.g., from other services)
    // and are not persisted in the database.

    @Transient
    private String entrepriseNom; // Company name (fetched from Entreprise service)

    @Transient
    private String entrepriseLogo; // Company logo path (fetched from Entreprise service)

    @Transient
    private Long nombreCandidatures; // Number of applications received (fetched from Candidature service)
}