spring.application.name=frontend-skillmatch


server.port=8086


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML


api.gateway.url=${API_GATEWAY_URL:http://localhost:8080}


spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:consul-server-skillmatchpfe}
spring.cloud.consul.port=${SPRING_CLOUD_CONSUL_PORT:8500}
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}


spring.cloud.consul.discovery.prefer-ip-address=true

spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=15s
spring.cloud.consul.discovery.fail-fast=false
spring.cloud.consul.discovery.register-health-check=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

spring.main.allow-bean-definition-overriding=true





logging.level.com.ines.frontend_skillmatch=DEBUG
logging.level.com.ines.frontend_skillmatch.service.client=DEBUG